<a href="https://colab.research.google.com/github/fernandovidalnn/evaluacion_1_mineria_datos/blob/main/ev1_mineria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[LINK FUENTE DE DATOS](https://www.kaggle.com/datasets/anbudanadithya/spotify-music)

https://www.kaggle.com/datasets/anbudanadithya/spotify-music

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('Spotify_Music.csv')

In [3]:
# Para ver todas las columnas sin cortes
pd.set_option('display.max_columns', None)

# Para ver todas las filas (cuidado si el dataset es muy grande)
#pd.set_option('display.max_rows', None)

In [4]:
df.shape # visualizamos la cantidad de filas y columnas

(114000, 21)

In [5]:
df.head() #Visualizacion de las primeras 5 filas

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [6]:
df.tail() # visualización de las ultimas 5 filas

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,5,-16.393,1,0.0422,0.640,0.928,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,0,-18.318,0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,0,-10.895,0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,7,-10.889,1,0.0297,0.381,0.000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,1,-10.204,0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4,world-music

In [7]:
df.dtypes #vemos el tipo de dato de cada columna

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [8]:
df.isnull().sum() #contamos la cantidad de nulos por columna

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [9]:
 # Valores nulos
for feature in df.columns:
  print('Total de valores nulos de', feature, '=', df[feature].isna().sum())

Total de valores nulos de Unnamed: 0 = 0
Total de valores nulos de track_id = 0
Total de valores nulos de artists = 1
Total de valores nulos de album_name = 1
Total de valores nulos de track_name = 1
Total de valores nulos de popularity = 0
Total de valores nulos de duration_ms = 0
Total de valores nulos de explicit = 0
Total de valores nulos de danceability = 0
Total de valores nulos de energy = 0
Total de valores nulos de key = 0
Total de valores nulos de loudness = 0
Total de valores nulos de mode = 0
Total de valores nulos de speechiness = 0
Total de valores nulos de acousticness = 0
Total de valores nulos de instrumentalness = 0
Total de valores nulos de liveness = 0
Total de valores nulos de valence = 0
Total de valores nulos de tempo = 0
Total de valores nulos de time_signature = 0
Total de valores nulos de track_genre = 0

Podemos ver que contamos con un dataset casi completamente limpio y existe 1 nulo en 3 columanas distintas (artists, album_name y track_name) el resto de columnas no contienen nulos.

Realizaremos una aliminacion completa de los nulos.

In [10]:
df = df.dropna() #eliminacion de nulos completa y agresiva

confirmaremos la eliminación de los nulos.

In [11]:
 # Valores nulos
for feature in df.columns:
  print('Total de valores nulos de', feature, '=', df[feature].isna().sum())

Total de valores nulos de Unnamed: 0 = 0
Total de valores nulos de track_id = 0
Total de valores nulos de artists = 0
Total de valores nulos de album_name = 0
Total de valores nulos de track_name = 0
Total de valores nulos de popularity = 0
Total de valores nulos de duration_ms = 0
Total de valores nulos de explicit = 0
Total de valores nulos de danceability = 0
Total de valores nulos de energy = 0
Total de valores nulos de key = 0
Total de valores nulos de loudness = 0
Total de valores nulos de mode = 0
Total de valores nulos de speechiness = 0
Total de valores nulos de acousticness = 0
Total de valores nulos de instrumentalness = 0
Total de valores nulos de liveness = 0
Total de valores nulos de valence = 0
Total de valores nulos de tempo = 0
Total de valores nulos de time_signature = 0
Total de valores nulos de track_genre = 0

Revisaremos con cuantas filas quedó el df luego de la eliminación de los nulos

In [12]:
df.shape

(113999, 21)

Aplicamos dropna y eliminamos los nulos presentes que al finalizar vemos que era solo 1 fila que contenia 3 nulos en 3 columnas distintas

In [13]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

# **MAPEO DE DATOS**

## **Realizaremos un mapeo de datos de tu dataset de Spotify:**

Unnamed: 0: Numérico Discreto (Índice o conteo de filas)

track_id: Categórico Nominal (Identificador único de texto)

artists: Categórico Nominal

album_name: Categórico Nominal

track_name: Categórico Nominal

popularity: Numérico Discreto (Escala de 0 a 100)

duration_ms: Numérico Discreto (Tiempo expresado en milisegundos)

explicit: Categórico Nominal (Variable booleana/binaria)

danceability: Numérico Continuo

energy: Numérico Continuo

key: Categórico Ordinal (Representa notas musicales con un orden técnico,
aunque a veces se trata como nominal)

loudness: Numérico Continuo (Decibelios)

mode: Categórico Nominal (Binario: Mayor o Menor)

speechiness: Numérico Continuo

acousticness: Numérico Continuo

instrumentalness: Numérico Continuo

liveness: Numérico Continuo

valence: Numérico Continuo

tempo: Numérico Continuo (BPM)

time_signature: Numérico Discreto (Compás musical)

track_genre: Categórico Nominal


## **Clasificación de Variables:**

* Categórico Nominal:
Categorías sin un orden o jerarquía específica.
Ejemplo: track_id, artists, track_genre.
* Categórico Ordinal:
Categorías que siguen un orden lógico o escala.
Ejemplo: key (en contextos musicales) o niveles de popularidad si se agruparan por rangos (Baja, Media, Alta).
* Numérico Discreto:
Valores que surgen de un conteo y no admiten decimales en su unidad base.
Ejemplo: duration_ms, popularity, time_signature.
* Numérico Continuo:
Valores que resultan de una medición y pueden tener decimales.
Ejemplo: danceability, energy, loudness, tempo.